---

- name: Setup apps
  hosts: local
  gather_facts: yes
  tasks:
    - name: "[BREW] Install packages"
      community.general.homebrew:
        name: 
          - alacritty
          - antigen
          - docker
          - fd
          - font-jetbrains-mono-nerd-font
          - fzf
          - git
          - helm
          - kubectl
          - lazygit
          - mise
          - neovim
          - ranger
          - ripgrep
          - spotify
          - stow
          - tldr
          - tmux
          - tmuxinator
          - unzip
          - xclip
        state: present
