---
- name: Setup mise
  hosts: local
  tasks:
    - name: "[MISE] Install mise languages"
      ansible.builtin.shell: 
        cmd: "mise use --global {{ item.name }}@{{ item.version }}"
        creates: "~/.local/share/mise/shims/{{ item.cmd | default(item.name) }}"
      with_items:
        - name: node
          version: 22.16.0
        - name: go
          version: 1.24.3
        - name: java
          version: 22.0.2
        - name: lua
          version: 5.4.7
        - name: rust
          cmd: cargo
          version: 1.87.0
